### ISSUE TITLE
pinned notices

### ISSUE THREAD

**Issue by NISH1001** [coders-circle/Notifica#6]
How about considering **pinned** notices too. Would be legit...

**Comment by FrozenHelium** [comment]
Indeed. Soon to be implemented

**Comment by NISH1001** [comment]
and on web interface, how about adding default value to "next day" when CR assigns a notice. This way, by accidental "today" date the notice shall not be "delete or not shown" the next day.

**Comment by FrozenHelium** [comment]
Pinned <b>Notices</b> and <b>Assignments</b> has been implemented.
